# ============================================================
# Standardwerte für Codelists
# Können bei einer einzelnen Codelist überschrieben werden.
# ============================================================

default.keyColumn=code
default.valueColumn=wert

default.rowElement=Row
default.valueElement=Value
default.columnAttribute=ColumnRef
default.simpleValueElement=SimpleValue


# ============================================================
# Rollenbezeichnungen
# Verwendung in Input.htm: codelist:rollenbezeichnung
# ============================================================

rollenbezeichnung.file=GDS.Rollenbezeichnung-3.5.xml


# ============================================================
# Art des Ersuchens um Sachentscheidung
# Verwendung in Input.htm: codelist:ersuchenSachentscheidung
# ============================================================

ersuchenSachentscheidung.file=ENOVA.ErsuchenSachentscheidung-1.0.xml

# ============================================================
# Sachentscheidung
# Verwendung für die Auswahl im Antwortformular
# ============================================================

sachentscheidung.file=ENOVA.Sachentscheidung-1.0.xml

# ============================================================
# Telekommunikationsart
# Verwendung in Input.htm und Output.htm
# ============================================================

telekommunikationsart.file=GDS.Telekommunikationsart-2.3.xml