# ============================================================
# Standardwerte für Codelists
# Können bei einer einzelnen Codelist überschrieben werden.
# ============================================================

default.keyColumn=code
default.valueColumn=wert

default.rowElement=Row
default.valueElement=Value
default.columnAttribute=ColumnRef
default.simpleValueElement=SimpleValue


# ============================================================
# Rollenbezeichnungen
# Verwendung in Input.htm: codelist:rollenbezeichnung
# ============================================================

rollenbezeichnung.file=GDS.Rollenbezeichnung-3.5.xml


# ============================================================
# Art des Ersuchens um Sachentscheidung
# Verwendung in Input.htm: codelist:ersuchenSachentscheidung
# ============================================================

ersuchenSachentscheidung.file=ENOVA.ErsuchenSachentscheidung-1.0.xml