@startuml
title eNoVa-Editor – Fachassistent-Ablauf (XJustiz eNoVA 2900003)

start

partition "JavaFX-Anwendung" {
    :EnovaEditorApplication startet;
    :Bildschirmgröße ermitteln & Fenster zentrieren;
    :main-view.fxml wird geladen;
    :caseworkers.xml einlesen (schemafreie CDATA-Fragmente);
    :codelists/ENOVA.Sachentscheidung einlesen (Genericode);
}

partition "MainController" {
    :Eingangsdaten laden (Dateidialog / Musterdaten);
}

if (XML-Datei ausgewählt?) then (ja)

    partition "XmlLoader & ErsuchenSachentscheidungChecker" {
        :XML-Datei einlesen (DOM Document);
        :Prüfen, ob Nachricht eNoVa 2900003 ist;
        if (Nachricht gültig?) then (ja)
        else (nein)
            :Fehlermeldung anzeigen;
            detach
        endif
    }

    partition "TemplateLoader & XPathTemplateRenderer" {
        :Input.htm einlesen & rendern;
        :HTML im Standard-Browser öffnen;
    }

    partition "Sachbearbeitung (Entscheidungserfassung)" {
        :Sachbearbeiter(in) auswählen;
        :Aktenzeichen der Kommune erfassen;
        :Art der Sachentscheidung wählen (aus Genericode-Codeliste);
    }

    partition "Antwort & Export" {
        if (Aktion?) then (Vorschau)
            :EnovaResponseTransformer transformiert 2900003 Ersuchen in Sachentscheidung;
            :Output.htm Template rendern & im Browser anzeigen;
        else (Export)
            :EnovaResponseTransformer transformiert 2900003;
            :nachricht.enova.entscheidung.2900003.xml speichern;
            :Output.htm Bescheid speichern;
            note right
                Bereit zur qualifizierten
                Signatur (qeS / CAdES detached)
                für die Rückübermittlung via beBPo
            end note
            :Erfolgsmeldung anzeigen;
        endif
    }

else (nein)
    :Warten auf Dateiauswahl oder Klick auf "Musterdaten laden";
endif

stop

@enduml